#!/usr/bin/python3

import sys
import random
import time

def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

def prime_factors(n):
    factors = []
    divisor = 2
    while n > 1:
        while n % divisor == 0:
            factors.append(divisor)
            n //= divisor
        divisor += 1
        while not is_prime(divisor):
            divisor += 1
    return factors

if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

input_file = sys.argv[1]

try:
    with open(input_file, 'r') as file:
        line = file.readline().strip()
        number = int(line)
        factors = prime_factors(number)
        if len(factors) == 2:
             p = factors[0]
            q = factors[1]
            print(f"{number}={p}*{q}")
        else:
            print(f"{number} is not a product of two prime numbers.")

except FileNotFoundError:
    print(f"Error: File '{input_file}' not found.")
    sys.exit(1)
except ValueError:
    print("Error: Invalid input in the file. The line should contain a valid natural number.")
    sys.exit(1)

